apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: localhost:5432
    database: cherryquant
    user: cherryquant
    password: cherryquant123
    secureJsonData:
      password: cherryquant123
    jsonData:
      sslmode: disable
      postgresVersion: 1300
      timescaledb: true